# Generated by Django 6.0.1 on 2026-01-21 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_promotion_until_date_review_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='discount_percent',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='until_date',
        ),
    ]
